ALTER TABLE "Provider"
  ADD COLUMN IF NOT EXISTS "photoUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "verifiedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "verifiedByAdmin" INTEGER,
  ADD COLUMN IF NOT EXISTS "ratingAverage" DOUBLE PRECISION DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "ratingCount" INTEGER NOT NULL DEFAULT 0;
